Integrate rofiFirmware into rmake ecosystem
paradise-fi/RoFI pull request #130
Opened 2022-02-14 15:18 UTC by yaqwsx

2022-02-16 23:06 UTC, ficap requested changes

2022-02-16 23:06 UTC, ficap commented on releng/tools/_idf_monitor.py
> +#!python
this shebang does not seem to work with bash. I suggest to use something like `#!/usr/bin/env python`

2022-02-16 23:06 UTC, ficap commented on releng/tools/rflash
> +#!python
this shebang does not seem to work with bash. I suggest to use something like `#!/usr/bin/env python3`

2022-02-16 23:06 UTC, ficap commented on releng/tools/rmonitor
> +#!python
this shebang does not seem to work with bash. I suggest to use something like `#!/usr/bin/env python`

2022-02-17 10:57 UTC, ficap commented on examples/hal/wifi/partitions.csv
> -# ESP-IDF Partition Table
this one will most probably be needed because final binary cannot fit into default 1M partition

2022-02-17 11:02 UTC, Ondraceq reviewed
Musím se ještě podívat na `rofi_hal.hpp`.
Nemám příležitost si to vyzkoušet, ale přijde mi to v pořádku (nevím jak `hal`).

2022-02-18 10:03 UTC, merged

2022-02-18 10:11 UTC, yaqwsx commented on .github/workflows/build.yml
> +          image: yaqwsx/rofi.desktop
Nn, všechno se asi postupně zmigruje do jednoho obrazu - do dektopu už totiž jen chybí GCC pro ARM.