Fix #131 and fix #133
paradise-fi/RoFI pull request #134
Opened 2022-02-18 11:54 UTC by yaqwsx

2022-02-18 13:25 UTC, yaqwsx commented on setup.sh
> -        PS1="$ORIGINAL_PS1"
The exit code is propagated correctly. Just when you have a status of the last command shown in the prompt overwriting `PS1` will expand all variables and thus, you don't see when the command failed. This was the reason why #132 was reported.

2022-02-18 16:18 UTC, vlstill reviewed
The changes so fare seem good by me. However, `rmake doc` can still fail if doxigen extensions (such as `breathe`) are not installed:

```
Extension error:
Could not import extension breathe (exception: No module named 'breathe')
make[2]: *** [doc/CMakeFiles/doc.dir/build.make:98: web/index.html] Error 2
make[1]: *** [CMakeFiles/Makefile2:98: doc/CMakeFiles/doc.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
Build of suite doc failed with Command '['cmake', '--build', '/home/xstill/repo/rofi/build.Release/doc', '-j18']' returned non-zero exit status 2.. See output above
```

2022-02-18 18:50 UTC, vlstill commented on setup.sh
> +        pip install sphinx breathe recommonmark sphinx_rtd_theme
OK, in that case it seems reasonable to me to install the packages locally even if they are available in system.

2022-02-18 18:52 UTC, vlstill approved these changes

2022-02-20 18:15 UTC, Ondraceq requested changes

2022-02-20 18:48 UTC, yaqwsx commented on setup.sh
> -        PS1="$ORIGINAL_PS1"
The general use is to open up a shell, set up the environment, work, kill the shell.

This is a workaround that doesn't properly work with the teardown or repeated invocation. In this way, it just does the least harm if you don't want to alter the shell. And I am not feeling like spending a lot of time on this here. True; we could probably backup PS1 only when it is changed. Would that seem sufficient to you?

2022-02-20 19:22 UTC, Ondraceq commented on setup.sh
> -        PS1="$ORIGINAL_PS1"
I'm more concerned about the fact that sometimes we show information that is not true, but I agree that it's not an important issue. Now I feel like creating an issue with the `won't fix` label documenting it is enough.

2022-02-20 19:22 UTC, Ondraceq approved these changes

2022-02-20 19:23 UTC, yaqwsx commented on setup.sh
> -        PS1="$ORIGINAL_PS1"
...or let's get rid of the shell alternation. Is there anyone actually using it?

2022-02-20 19:29 UTC, vlstill commented
Just a note on shell alteration… it would be quite easy to export something like ROFI_PROMPT_ID and let the users who want to see it add '$ROFI_PROMPT_ID' to their PS1… I will cost almost nothing to have it there permanently and it would work safely for anyone who works with RoFI suite often and wants shell indication.

2022-02-20 19:31 UTC, yaqwsx commented
I like the simplicity of that!

2022-02-20 19:32 UTC, Ondraceq commented on setup.sh
> -        PS1="$ORIGINAL_PS1"
I'm using it, but don't know how much attention I actually put to it

2022-02-21 11:20 UTC, merged