rofiTool: add shape command
paradise-fi/RoFI pull request #272
Opened 2022-11-30 17:08 UTC by Jaromel-Tuzerad

Adds shape command to rofi-tool, which takes two configurations (rofiworlds) and decides whether their physical shape is equal or not.

First commit implements isometry of points (and rofiworlds).
Second commit are minor improvements related to rofiworld decomposition functions.
Third commit implements command with the aforementioned functionality.

2022-12-01 15:14 UTC, Ondraceq reviewed
Two things:
- Don't write that you assume the Module to be an Universal Module if it doesn't have to be.
- Use `Vector` and `Matrix` from `configuration/Matrix.h` instead of using your own implementation (it has rotate, equal, etc...)

If you don't know why to use 4x4 matrices, ask @yaqwsx 

I didn't check the whole code since this is a large part of it

2022-12-01 15:14 UTC, Ondraceq commented on softwareComponents/isoreconfig/include/isoreconfig/isomorphic.hpp
> + * @brief Creates a container of positions from a given universal module <mod> by
Remove the "universal" - it should work for any module (if not, take `UniversalModule` directly instead od `Module`.

2022-12-01 15:14 UTC, Ondraceq commented on softwareComponents/isoreconfig/include/isoreconfig/isomorphic.hpp
>   * Assumes the module is a UniversalModule.
The same... if you really assume it, take it as `UniversalModule`

2022-12-01 15:14 UTC, Ondraceq commented on softwareComponents/isoreconfig/include/isoreconfig/isomorphic.hpp
> + * Assumes the world consists only of UniversalModules.
Again - don't assume universal modules - there is no need.

2023-02-03 08:07 UTC, yaqwsx requested changes

2023-02-03 08:07 UTC, yaqwsx commented on softwareComponents/isoreconfig/src/isomorphic.cpp
> +    result(3) = 1;
Armadillo používá pro indexaci kulaté závorky? A čistě hypoteticky - nemělo by tam samo o sobě vždy vyjít 1?

2023-02-03 08:07 UTC, yaqwsx commented on tools/rofiTool/rendering.cpp
> +    std::array< Points, 2 > origPts = decomposeRofiWorld( world );
Kdybys chtěl, tak můžeš použít structured binding a dát tomu jména (nikde totiž `origPts` neiteruješ):
```.cpp
auto [roficomPoints, modulePoints] = decomposeRofiWorld( world );
```

2023-02-03 13:33 UTC, Ondraceq commented on softwareComponents/isoreconfig/src/isomorphic.cpp
> +    result(3) = 1;
jo, armadillo je divný -_-

2023-02-04 14:15 UTC, Jaromel-Tuzerad reviewed
Upravil jsem reprezentaci Cloud, aby používala pro kontejner bodů vector< array< int, 3 > >, což se mi zdálo nejrozumější; viz mé reakce na zpětnou vazbu.

2023-02-14 18:05 UTC, xondika commented on tools/rofiTool/shape.cpp
> +        exit( int(firstWorld->modules().size() + secondWorld->modules().size()) );
Proč je tady exit a všude jinde je chybová hláška a return?

2023-10-10 07:45 UTC, yaqwsx approved these changes

2023-10-10 07:45 UTC, yaqwsx approved these changes

2023-10-10 12:09 UTC, merged