Compiling without gazebo
paradise-fi/RoFI pull request #77
Opened 2021-09-13 16:41 UTC by Ondraceq

Resolves #76

2021-09-13 16:41 UTC, Ondraceq commented
TODO checks:
 - [ ] build with gazebo (removed global linking)
 - [ ] build docs without gazebo installed
 - [ ] build world-creator (the armadillo dependency in cmake was removed - use ${ARMADILLO_LIBRARIES} if needed)

2021-09-16 07:03 UTC, yaqwsx requested changes
I am not sure if I follow what "build world-creator (the armadillo dependency in cmake was removed - use ${ARMADILLO_LIBRARIES} if needed)" means.

2021-09-16 07:03 UTC, yaqwsx commented on softwareComponents/gazebosim/common/CMakeLists.txt
> +target_include_directories(rofiPluginCommon INTERFACE ${GAZEBO_INCLUDE_DIRS})
Please consider merging these two lines (5 & 6)

2021-09-16 10:38 UTC, Ondraceq commented
> 
> I am not sure if I follow what "build world-creator (the armadillo dependency in cmake was removed - use ${ARMADILLO_LIBRARIES} if needed)" means.

It was just a reminder to check if the tool compiles, because I didn't have the library available at the moment

2021-09-17 09:04 UTC, yaqwsx approved these changes

2021-09-17 09:04 UTC, merged